run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

version: 2

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  revive:
    enable-all-rules: false
    rules:
      - name: add-constant
      - name: argument-limit
      - name: atomic
      - name: banned-characters
      - name: bare-return
      - name: blank-imports
      - name: bool-literal-in-expr
      - name: call-to-gc
      - name: cognitive-complexity
      - name: comment-spacings
      - name: comments-density
      - name: confusing-naming
      - name: confusing-results
      - name: constant-logical-expr
      - name: context-as-argument
      - name: context-keys-type
      - name: cyclomatic
      - name: datarace
      - name: deep-exit
      - name: defer
      - name: dot-imports
      - name: duplicated-imports
      - name: early-return
      - name: empty-block
      - name: empty-lines
      - name: epoch-naming
      - name: enforce-map-style
      - name: enforce-repeated-arg-type-style
      - name: enforce-slice-style
      - name: enforce-switch-style
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      - name: file-header
      - name: file-length-limit
      - name: filename-format
      - name: flag-parameter
      - name: forbidden-call-in-wg-go
      - name: function-length
      - name: function-result-limit
      - name: get-return
      - name: identical-branches
      - name: identical-ifelseif-branches
      - name: identical-ifelseif-conditions
      - name: identical-switch-branches
      - name: identical-switch-conditions
      - name: if-return
      - name: import-alias-naming
      - name: import-shadowing
      - name: imports-blocklist
      - name: increment-decrement
      - name: indent-error-flow
      - name: inefficient-map-lookup
      - name: line-length-limit
      - name: max-control-nesting
      - name: max-public-structs
      - name: modifies-parameter
      - name: modifies-value-receiver
      - name: nested-structs
      - name: optimize-operands-order
      - name: package-comments
      - name: package-directory-mismatch
      - name: range-val-address
      - name: range-val-in-closure
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: redundant-build-tag
      - name: redundant-import-alias
      - name: redundant-test-main-exit
      - name: string-format
      - name: string-of-int
      - name: struct-tag
      - name: superfluous-else
      - name: time-date
      - name: time-equal
      - name: time-naming
      - name: unchecked-type-assertion
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unexported-return
      - name: unhandled-error
      - name: unnecessary-if
      - name: unnecessary-format
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unsecure-url-scheme
      - name: unused-parameter
      - name: unused-receiver
      - name: use-any
      - name: use-errors-new
      - name: use-fmt-print
      - name: use-waitgroup-go
      - name: useless-break
      - name: useless-fallthrough
      - name: var-declaration
      # - name: var-naming
      - name: waitgroup-by-value
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/n-r-w/squirrel
  nolintlint:
    require-explanation: true
    require-specific: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  disable-all: true
  enable:
    - godot
    - copyloopvar
    - gocyclo
    - misspell
    - rowserrcheck
    - staticcheck
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    # - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - loggercheck
    - makezero
    - mirror
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - sloglint
    - sqlclosecheck
    - testableexamples
    - testifylint
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - paralleltest

  exclusions:
    generated: lax
    rules:
      - linters:
          - perfsprint
          - dupl
          - gochecknoglobals
          - gocognit
          - goconst
          - gocritic
          - gosec
          - govet
          - lll
          - revive
          - staticcheck
          - unparam
          - whitespace
          - gocyclo
          - cyclop
        path: _test\.go

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: error
  case-sensitive: false

formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - loadtest$
      - profile$
      - bench$
