# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
run:
  timeout: 1m
  issues-exit-code: 1
  tests: true
  skip-dirs:
  skip-files:
    - (.+)_mock.go$

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  revive:
    rules:
      - name: var-naming
        disabled: true
  stylecheck:
    checks: ["all", "-ST1003", "-ST1012"]
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - unlabelStmt # false positive
      - sloppyReassign # quite strange linter, suggests performing "shadows declaration" inside if.
    settings:
      # don't forget to run "golangci-lint cache clean" after changes in the .go files below
      hugeParam:
        sizeThreshold: 512
      rangeValCopy:
        sizeThreshold: 512

linters:
  disable-all: true
  enable:
    # - dupl - it's very slow, enable if you really know why you need it
    - errcheck
    # - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - megacheck # (staticcheck + gosimple + unused in one linter)
    - revive
    - typecheck
    - unused # will be used insted of varcheck + deadcode + structcheck. More info https://github.com/golangci/golangci-lint/issues/1841
    # - gocritic
    # - gocognit
    - gomnd
    - prealloc
    - unparam
    - staticcheck
    # - paralleltest
    - exhaustive

issues:
  exclude-use-default: false
  exclude:
    # _ instead of err checks
    - G104
    # for "public interface + private struct implementation" cases only!
    - exported func .* returns unexported type .*, which can be annoying to use
    # can be removed in the development phase
    # - (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
    # not for the active development - can be removed in the stable phase
    - should have a package comment
    - don't use an underscore in package name
    # EXC0001 errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
    - should check returned error before deferring
  exclude-rules:
    - path: _test\.go
      linters:
        - gocognit
        - gocritic
        - unparam
  max-issues-per-linter: 0
  max-same-issues: 0
